// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS131PYy-Rc0RMPP8JS4cZkuu4q570PW4',
    appId: '1:325226809073:web:d423bcd81a27e2f24b0b50',
    messagingSenderId: '325226809073',
    projectId: 'truckfix-f840b',
    authDomain: 'truckfix-f840b.firebaseapp.com',
    storageBucket: 'truckfix-f840b.firebasestorage.app',
    measurementId: 'G-QVX29ZHXB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEa3x1Yu5g9gHOnU8ohgNkGkSDHFl5c20',
    appId: '1:345308459087:android:f812a364816667c8f83a3a',
    messagingSenderId: '345308459087',
    projectId: 'delivery-app-frontend-key',
    storageBucket: 'delivery-app-frontend-key.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM7YtvFJCwm7juGsY1hAONd8Ubqdcgyx8',
    appId: '1:345308459087:ios:68c7ad4d55bdd6b9f83a3a',
    messagingSenderId: '345308459087',
    projectId: 'delivery-app-frontend-key',
    storageBucket: 'delivery-app-frontend-key.firebasestorage.app',
    iosClientId:
        '345308459087-uuskhgtblkuggulv315mjfelu6ofdmfa.apps.googleusercontent.com',
    iosBundleId: 'bh.yjeek.customer',
  );
}
