// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS131PYy-Rc0RMPP8JS4cZkuu4q570PW4',
    appId: '1:325226809073:web:d423bcd81a27e2f24b0b50',
    messagingSenderId: '325226809073',
    projectId: 'truckfix-f840b',
    authDomain: 'truckfix-f840b.firebaseapp.com',
    storageBucket: 'truckfix-f840b.firebasestorage.app',
    measurementId: 'G-QVX29ZHXB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXOCiAKHOn3Hj52hJhXe9HspnpHSf78nQ',
    appId: '1:325226809073:android:06aba97a954280a24b0b50',
    messagingSenderId: '325226809073',
    projectId: 'truckfix-f840b',
    storageBucket: 'truckfix-f840b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tHRUuj5UgMrETEgudL_QFAh6dZobq48',
    appId: '1:325226809073:ios:28aa3396a5b070624b0b50',
    messagingSenderId: '325226809073',
    projectId: 'truckfix-f840b',
    storageBucket: 'truckfix-f840b.firebasestorage.app',
    iosBundleId: 'bh.yjeek.customer',
  );
}
