# -*- coding: utf-8 -*-
"""Extra Arabic translations for remaining extracted strings."""
MORE_AR = {
    "Enter the 4-digit code sent to {phone}.": "أدخل الرمز المكوّن من 4 أرقام المرسل إلى {phone}.",
    "Incorrect code. {attempts} attempts left.": "رمز غير صحيح. تبقى {attempts} محاولات.",
    "1 item · Order $waitingOrderId": "صنف واحد · طلب $waitingOrderId",
    "15–25 min": "15–25 دقيقة",
    "15–25 min · Standard": "15–25 دقيقة · قياسي",
    "2 items": "صنفان",
    "2% cashback to your Yjeek Wallet": "2٪ كاش باك إلى محفظة يجيك",
    "3 items · Order $orderIdShort": "3 أصناف · طلب $orderIdShort",
    "4 items · Order $waitingOrderId": "4 أصناف · طلب $waitingOrderId",
    "Accepted: Visa/Mastercard, BenefitPay, and Yjeek Wallet credits. Payments are processed via PCI-DSS compliant gateways. All prices in BHD; VAT 10% where applicable.": "المقبول: فيزا/ماستركارد، بنفت باي، ورصيد محفظة يجيك. تُعالج المدفوعات عبر بوابات متوافقة مع PCI-DSS. جميع الأسعار بالدينار البحريني؛ ضريبة القيمة المضافة 10٪ حيث تنطبق.",
    "Ahmed K. · your champ": "أحمد ك. · الشامب الخاص بك",
    "Allergies, seating, less spicy…": "حساسية، جلوس، أقل حاراً…",
    "ARRIVAL CODE": "رمز الوصول",
    "Balance BHD 12.450": "الرصيد 12.450 د.ب",
    "Be first on the Zood waiting list": "كن أولاً في قائمة انتظار Zood",
    "Book again": "احجز مجدداً",
    "Booking": "حجز",
    "Booking confirmed!": "تم تأكيد الحجز!",
    "Booking summary": "ملخص الحجز",
    "Brew & Bean said yes! 🙌": "Brew & Bean وافق! 🙌",
    "BREW & BEAN · PICKUP": "BREW & BEAN · استلام",
    "Brew & Bean · ready in ~8 min": "Brew & Bean · جاهز خلال ~8 دقائق",
    "Cancel booking": "إلغاء الحجز",
    "Candles & a little surprise on the table.": "شموع ومفاجأة صغيرة على الطاولة.",
    "Card · ending 4421": "بطاقة · تنتهي بـ 4421",
    "Cashback (min 3% of order value) is valid for 6 months from the credit date (rolling expiry). Withdrawals need a min BHD 10 balance; the customer receives 70% and Yjeek retains a 30% processing fee. Processing takes 3–7 working days.": "الكاش باك (حد أدنى 3٪ من قيمة الطلب) صالح لمدة 6 أشهر من تاريخ الإضافة (انتهاء متجدد). السحب يتطلب رصيداً لا يقل عن 10 د.ب؛ يحصل العميل على 70٪ وتحتفظ يجيك برسوم معالجة 30٪. تستغرق المعالجة 3–7 أيام عمل.",
    "Change address": "تغيير العنوان",
    "Choose another address": "اختر عنواناً آخر",
    "Choose where to deliver": "اختر مكان التوصيل",
    "Choose your time. Kitchen starts on check-in.": "اختر وقتك. يبدأ المطبخ عند تسجيل الوصول.",
    "Collect at": "الاستلام من",
    "Complete payment within 2 minutes. If payment is not completed in time, your order will be cancelled automatically.": "أكمل الدفع خلال دقيقتين. إذا لم يكتمل الدفع في الوقت، يُلغى طلبك تلقائياً.",
    "Complete payment within 5 minutes": "أكمل الدفع خلال 5 دقائق",
    "Complete payment within 5 minutes. If payment is not completed in time, your order will be cancelled automatically.": "أكمل الدفع خلال 5 دقائق. إذا لم يكتمل الدفع في الوقت، يُلغى طلبك تلقائياً.",
    "Confirm location": "تأكيد الموقع",
    "Contact support": "تواصل مع الدعم",
    "Contact venue": "تواصل مع المكان",
    "Customer app (iOS & Android) · www.yjeektech.com · Yjeek Wallet (cashback) · Yjeek Discover.": "تطبيق العملاء (iOS و Android) · www.yjeektech.com · محفظة يجيك (كاش باك) · Yjeek Discover.",
    "Delete address": "حذف العنوان",
    "Delete this address?": "حذف هذا العنوان؟",
    "Deliver here": "وصّل هنا",
    "Delivered!": "تم التوصيل!",
    "Delivery method": "طريقة التوصيل",
    "Detect my GPS location": "تحديد موقعي عبر GPS",
    "DETECTED LOCATION": "الموقع المحدد",
    "Dine-in basket": "سلة تناول الطعام",
    "Dine-in checkout": "دفع تناول الطعام",
    "Dine-in order": "طلب تناول في المطعم",
    "Dine-in preferences": "تفضيلات تناول الطعام",
    "Dine-in time": "وقت تناول الطعام",
    "Dining option": "خيار الجلوس",
    "Edit address": "تعديل العنوان",
    "Electronics · #$orderId": "إلكترونيات · #$orderId",
    "Enjoy your meal": "بالعافية",
    "Flat / Floor": "الشقة / الطابق",
    "Free cancellation before the provider accepts.": "إلغاء مجاني قبل قبول مقدّم الخدمة.",
    "Free cancellation before the vendor accepts": "إلغاء مجاني قبل قبول المتجر",
    "Free cancellation before the vendor accepts.": "إلغاء مجاني قبل قبول المتجر.",
    "Get directions": "الحصول على الاتجاهات",
    "Get early access to member discounts, cashback and exclusive offers — before everyone else.": "احصل على وصول مبكر لخصومات الأعضاء والكاش باك والعروض الحصرية — قبل الجميع.",
    "Glow Beauty Lounge accepted! 🙌": "Glow Beauty Lounge وافق! 🙌",
    "Go to checkout": "اذهب لإتمام الطلب",
    "Go to verification": "اذهب للتحقق",
    "Haircut & styling": "قص وتصفيف",
    "Haircut & styling · Booking $bookingId": "قص وتصفيف · حجز $bookingId",
    "Hope you enjoyed your order from The Green Kitchen.": "نتمنى أنك استمتعت بطلبك من The Green Kitchen.",
    "Hope you enjoyed your visit to Glow Beauty Lounge.": "نتمنى أنك استمتعت بزيارتك لـ Glow Beauty Lounge.",
    "How would you like to dine?": "كيف تود أن تتناول طعامك؟",
    "ID verification": "التحقق من الهوية",
    "If payment is not completed in time, your order will be cancelled automatically.": "إذا لم يكتمل الدفع في الوقت، يُلغى طلبك تلقائياً.",
    "in ~1 hour": "خلال ~ساعة",
    "Indoor": "داخلي",
    "ITEM": "الصنف",
    "Join the Zood waiting list?": "الانضمام إلى قائمة انتظار Zood؟",
    "Join waiting list": "انضم لقائمة الانتظار",
    "Join Zood and save on every order": "انضم إلى Zood ووفّر في كل طلب",
    "Keep current cart": "الإبقاء على السلة الحالية",
    "Kitchen starts now. Table ready in ~1 hour.": "يبدأ المطبخ الآن. الطاولة جاهزة خلال ~ساعة.",
    "Live map tracking starts when the champ picks up your order.": "يبدأ التتبع على الخريطة عندما يستلم الشامب طلبك.",
    "Location photos · Optional": "صور الموقع · اختياري",
    "Message Ahmed…": "راسل أحمد…",
    "Method": "الطريقة",
    "Move the map to drop your pin": "حرّك الخريطة لوضع الدبوس",
    "Order #": "طلب #",
    "Order $orderId · Mon 14 Jun": "طلب $orderId · الإثنين 14 يونيو",
    "Order $orderId · Seef": "طلب $orderId · السيف",
    "Order confirmed": "تم تأكيد الطلب",
    "Order confirmed!": "تم تأكيد الطلب!",
    "Out of range for this vendor": "خارج نطاق هذا المتجر",
    "Outdoor": "خارجي",
    "PAID": "مدفوع",
    "Paid": "مدفوع",
    "Paid: BenefitPay": "مدفوع: بنفت باي",
    "Paid: Yjeek Wallet": "مدفوع: محفظة يجيك",
    "Party size": "عدد الأشخاص",
    "Pay & prep now": "ادفع وابدأ التحضير الآن",
    "PAY IN": "ادفع خلال",
    "Pay with": "ادفع عبر",
    "Payment window expired. Your order was cancelled.": "انتهت مهلة الدفع. تم إلغاء طلبك.",
    "People": "الأشخاص",
    "PICKUP": "استلام",
    "Pickup details": "تفاصيل الاستلام",
    "Pickup discount (15%)": "خصم الاستلام (15٪)",
    "Pickup from": "الاستلام من",
    "Pickup time ·": "وقت الاستلام ·",
    "Pickup · #$orderId": "استلام · #$orderId",
    "PICKUP · PAID": "استلام · مدفوع",
    "Place booking": "تأكيد الحجز",
    "Placing your order": "جاري تقديم طلبك",
    "Please collect on time. No-show within 1 hour of the ready time is non-refundable.": "يرجى الاستلام في الموعد. عدم الحضور خلال ساعة من وقت الجاهزية غير قابل للاسترداد.",
    "Popular with Haircut & styling": "شائع مع القص والتصفيف",
    "Prepare now": "حضّر الآن",
    "Prepare on arrival": "حضّر عند الوصول",
    "Preparing · Paid $orderTotal": "قيد التحضير · مدفوع $orderTotal",
    "Preparing · ready in ~8 min": "قيد التحضير · جاهز خلال ~8 دقائق",
    "PRICE": "السعر",
    "Print": "طباعة",
    "Rate the food": "قيّم الطعام",
    "Rate the provider": "قيّم مقدّم الخدمة",
    "Rate the service": "قيّم الخدمة",
    "Rate your experience": "قيّم تجربتك",
    "Ready in ~8 min": "جاهز خلال ~8 دقائق",
    "Same Day delivery": "توصيل في نفس اليوم",
    "Same Day · Apartment - Seef": "نفس اليوم · شقة - السيف",
    "Save a place for faster checkout": "احفظ مكاناً لإتمام الشراء بشكل أسرع",
    "Save more on every order with Zood — join the waiting list": "وفّر أكثر في كل طلب مع Zood — انضم لقائمة الانتظار",
    "scheduled cart: user can add items from different vendors, MAX 3": "السلة المجدولة: يمكن إضافة أصناف من متاجر مختلفة، بحد أقصى 3",
    "Scheduled delivery": "توصيل مجدول",
    "Search area, street or landmark...": "ابحث عن منطقة أو شارع أو معلم...",
    "Seating": "الجلوس",
    "Send to vendor": "أرسل إلى المتجر",
    "Sending to vendor…": "جاري الإرسال إلى المتجر…",
    "Sending your booking to Glow Beauty Lounge": "جاري إرسال حجزك إلى Glow Beauty Lounge",
    "Sending your dine-in order to VEERA": "جاري إرسال طلب تناول الطعام إلى VEERA",
    "Sent to Brew & Bean": "أُرسل إلى Brew & Bean",
    "Sent to Glow Beauty Lounge": "أُرسل إلى Glow Beauty Lounge",
    "Sent to Vapeology": "أُرسل إلى Vapeology",
    "Sent to VEERA": "أُرسل إلى VEERA",
    "Sent to vendor": "أُرسل إلى المتجر",
    "Service complete!": "اكتملت الخدمة!",
    "Service location": "موقع الخدمة",
    "Set your location": "حدّد موقعك",
    "Share receipt": "شارك الإيصال",
    "SHOW THIS AT THE COUNTER": "أظهر هذا عند الكاونتر",
    "Show this number to the vendor when you arrive at VEERA.": "أظهر هذا الرقم للمتجر عند وصولك إلى VEERA.",
    "Show this receipt at the counter to collect.": "أظهر هذا الإيصال عند الكاونتر للاستلام.",
    "Special occasion setup": "إعداد مناسبة خاصة",
    "Specialist": "أخصائي",
    "Start a new cart?": "بدء سلة جديدة؟",
    "Start new cart": "بدء سلة جديدة",
    "Start preparing now": "ابدأ التحضير الآن",
    "STATUS": "الحالة",
    "Submit & done": "إرسال وإنهاء",
    "Table": "طاولة",
    "Table for 2": "طاولة لشخصين",
    "Table ready": "الطاولة جاهزة",
    "Table ready in ~1 hour": "الطاولة جاهزة خلال ~ساعة",
    "Tap pay to complete": "اضغط ادفع للإكمال",
    "TECHHUB ELECTRONICS · SCHEDULED DELIVERY": "TECHHUB ELECTRONICS · توصيل مجدول",
    "Thanks for dining at VEERA · Adliya.": "شكراً لتناولك الطعام في VEERA · العدلية.",
    "This is an age-restricted (18+) order. You need to upload your CPR and documents and get verified before you can place this order.": "هذا طلب مقيّد بالعمر (18+). تحتاج إلى رفع CPR والمستندات والتحقق قبل تقديم هذا الطلب.",
    "Tip the specialist (optional)": "إكرامية للأخصائي (اختياري)",
    "Tip the staff (optional)": "إكرامية للطاقم (اختياري)",
    "Today · 19:30": "اليوم · 19:30",
    "Tomorrow · 10am–2pm": "غداً · 10ص–2م",
    "Total to pay": "المبلغ المستحق",
    "Track booking": "تتبّع الحجز",
    "Update this saved place": "تحديث هذا المكان المحفوظ",
    "Use current location": "استخدم الموقع الحالي",
    "Vape · #$orderId": "فيب · #$orderId",
    "Vapeology said yes! 🙌": "Vapeology وافق! 🙌",
    "VAPEOLOGY · VAPE DELIVERY": "VAPEOLOGY · توصيل فيب",
    "VAT (10%)": "ضريبة القيمة المضافة (10٪)",
    "VEERA accepted ✨": "VEERA وافق ✨",
    "VEERA · ADLIYA · DINE-IN": "VEERA · العدلية · تناول في المطعم",
    "VEERA · Adliya · Today 19:30": "VEERA · العدلية · اليوم 19:30",
    "Vendor accepted!": "قبل المتجر!",
    "Venue": "المكان",
    "VERIFIED ✓": "موثّق ✓",
    "Verify your age first": "تحقق من عمرك أولاً",
    "View order status": "عرض حالة الطلب",
    "View receipt": "عرض الإيصال",
    "Visit complete!": "اكتملت الزيارة!",
    "Waiting for the provider to accept your booking…": "بانتظار قبول مقدّم الخدمة لحجزك…",
    "Waiting for the vendor to accept your dine-in order…": "بانتظار قبول المتجر لطلب تناول الطعام…",
    "Waiting for the vendor to accept your order…": "بانتظار قبول المتجر لطلبك…",
    "When": "متى",
    "Where": "أين",
    "Write a review… (optional)": "اكتب مراجعة… (اختياري)",
    "Write a short review (optional)": "اكتب مراجعة قصيرة (اختياري)",
    "Yes, join the list": "نعم، انضم للقائمة",
    "Yjeek Electronics": "يجيك إلكترونيات",
    "Yjeek is a multi-category on-demand delivery and lifestyle platform operated by Yjeek Technologies W.L.L (CR 110111-3), Al Seef, Kingdom of Bahrain. Governed by the laws of Bahrain.": "يجيك منصة توصيل ونمط حياة متعددة الفئات تعمل بها يجيك تكنولوجيز ذ.م.م (س.ت 110111-3)، السيف، مملكة البحرين. تخضع لقوانين البحرين.",
    "Yjeek is a multi-category on-demand delivery and lifestyle platform operated by Yjeek Technologies W.L.L. We connect you with vendors and champs across 29 categories — food, groceries, dine-in, services, pickup and more.": "يجيك منصة توصيل ونمط حياة متعددة الفئات تعمل بها يجيك تكنولوجيز ذ.م.م. نربطك بالمتاجر والشامب عبر 29 فئة — طعام، بقالة، تناول في المطعم، خدمات، استلام والمزيد.",
    "Yjeek is a technology intermediary; vendors are solely responsible for their products. In-app prices must equal or be lower than in-store prices.": "يجيك وسيط تقني؛ المتاجر وحدها مسؤولة عن منتجاتها. يجب أن تكون أسعار التطبيق مساوية أو أقل من أسعار المتجر.",
    "You must be 18+, capable of entering contracts, and a resident or visitor in Bahrain. You are responsible for the security of your account credentials.": "يجب أن يكون عمرك 18+ وقادراً على إبرام العقود، ومقيماً أو زائراً في البحرين. أنت مسؤول عن أمان بيانات حسابك.",
    "Your appointment is booked · Ref #SV-4821": "تم حجز موعدك · مرجع #SV-4821",
    "Your booking": "حجزك",
    "Your cart has items from The Green Kitchen. Adding from Burger Boss will clear your current cart.": "سلتك تحتوي أصنافاً من The Green Kitchen. الإضافة من Burger Boss ستفرّغ سلتك الحالية.",
    "your champ": "الشامب الخاص بك",
    "Your CPR is verified by Yjeek. The champ still checks your ID (18+) on delivery.": "تم التحقق من CPR بواسطة يجيك. يتحقق الشامب من هويتك (18+) عند التسليم.",
    "Your CPR verifies your age for restricted items and your identity for wallet cash-out. IBAN details are used for withdrawals.": "يؤكد CPR عمرك للأصناف المقيّدة وهويتك لسحب المحفظة. تُستخدم بيانات IBAN للسحوبات.",
    "Your order is being prepared for delivery.": "طلبك قيد التحضير للتوصيل.",
    "Your order is being prepared for pickup.": "طلبك قيد التحضير للاستلام.",
    "Your service": "خدمتك",
    "Your table will be ready about 1 hour after you pay.": "ستكون طاولتك جاهزة بعد حوالي ساعة من الدفع.",
    "− BHD 0.975": "− 0.975 د.ب",
    "● Online · your champ": "● متصل · الشامب الخاص بك",
    "★ 4.9 · Motorcycle · M 1234": "★ 4.9 · دراجة نارية · M 1234",
    "✅ Confirmed · Wed 14 · 1:00 PM": "✅ مؤكد · الأربعاء 14 · 1:00 م",
    "✅ Delivered · Today 13:48": "✅ تم التوصيل · اليوم 13:48",
    "✓ DINE-IN · PAID": "✓ تناول في المطعم · مدفوع",
    "✓ ORDER CONFIRMED": "✓ تم تأكيد الطلب",
    "✓ SERVICE · PAID": "✓ خدمة · مدفوع",
    "✓ WELCOME10 applied": "✓ تم تطبيق WELCOME10",
    "✦ Zood": "✦ Zood",
    "👨‍🍳 Preparing · table ready ~1 hr": "👨‍🍳 قيد التحضير · الطاولة جاهزة ~ساعة",
    "📦 Packed · out for delivery · arrives in 30–45 mins": "📦 جاهز · خرج للتوصيل · يصل خلال 30–45 دقيقة",
    "📦 Packed · ships today · arrives tomorrow": "📦 جاهز · يشحن اليوم · يصل غداً",
    "🕒 45 min": "🕒 45 دقيقة",
}
